name: HorseMount
main: com.ktross.horsemount.HorseMount
version: 1.1.0
description: HorseMount is a flexible player mount system. It allows players to summon and dismiss horse mounts with a simple command. Players can also choose to set their default mount via command or sign from 140 different mount types.
author: ktross

commands:
  horsemount:
    description: HorseMount help command
    aliases: hm
    permission: horsemount.help
    permission-message: You do not have permission to use this command.
  mount:
    aliases: mnt
    description: Summon/dismiss a mount
    permission: horsemount.mount
    permission-message: You do not have permission to use this command.
  dismount:
    description: Dismiss a mount
    permission: horsemount.dismount
    permission-message: You do not have permission to use this command.
  setmount:
    description: Set your default mount
    permission: horsemount.setmount
    permission-message: You do not have permission to use this command.
  setarmor:
    description: Set your mounts default armor
    permission: horsemount.setarmor
    permission-message: You do not have permission to use this command.
  showmount:
    description: Show your default mount
    permission: horsemount.showmount
    permission-message: You do not have permission to use this command.
  spawnmount:
    description: Spawn an unrideable mount for display
    permission: horsemount.spawnmount
    permission-message: You do not have permission to use this command.

permissions:
  horsemount.*:
    description: Allows access to everything
    default: false
    children:
      horsemount.help: true
      horsemount.reload: true
      horsemount.mount: true
      horsemount.dismount: true
      horsemount.setmount: true
      horsemount.setarmor: true
      horsemount.signs.*: true
      horsemount.variant.*: true
      horsemount.style.*: true
      horsemount.color.*: true
      horsemount.armor.*: true
      horsemount.showmount: true
      horsemount.spawnmount: true
  horsemount.signs.*:
    description: Allows access to use and create signs
    default: false
    children:
      horsemount.signs.use: true
      horsemount.signs.create: true
  horsemount.variant.*:
    description: Allows access to all mount variants
    default: false
    children:
      horsemount.variant.horse: true
      horsemount.variant.mule: true
      horsemount.variant.donkey: true
      horsemount.variant.skeleton: true
      horsemount.variant.zombie: true
  horsemount.style.*:
    description: Allows access to all mount styles
    default: false
    children:
      horsemount.style.default: true
      horsemount.style.white: true
      horsemount.style.whitefield: true
      horsemount.style.whitedots: true
      horsemount.style.blackdots: true
  horsemount.color.*:
    description: Allows access to all mount colors
    default: false
    children:
      horsemount.color.white: true
      horsemount.color.creamy: true
      horsemount.color.chestnut: true
      horsemount.color.brown: true
      horsemount.color.black: true
      horsemount.color.gray: true
      horsemount.color.darkbrown: true
  horsemount.armor.*:
    description: Allows access to all mount armor
    default: false
    children:
      horsemount.armor.iron: true
      horsemount.armor.gold: true
      horsemount.armor.diamond: true
  horsemount.help:
    description: Allows you to run the help command
    default: true
  horsemount.reload:
    description: Allows you to reload the plugin config
    default: false
  horsemount.mount:
    description: Allows you to summon mounts
    default: false
  horsemount.showmount:
    description: Allows you to run the showmount command
    default: true
  horsemount.spawnmount:
    description: Allows you to run the spawnmount command
    default: false
  horsemount.dismount:
    description: Allows you to dismount horses
    default: true
  horsemount.signs.use:
    description: Allows you to use signs
    default: true
  horsemount.signs.create:
    description: Allows you to create signs
    default: false
  horsemount.setarmor:
    description: Allows you to set your default armor
    default: true
  horsemount.armor.iron:
    description: Allows you to use this horse armor
    default: false
  horsemount.armor.gold:
    description: Allows you to use this horse armor
    default: false
  horsemount.armor.diamond:
    description: Allows you to use this horse armor
    default: false
  horsemount.setmount:
    description: Allows you to set your default mount
    default: true
  horsemount.variant.horse:
    description: allows you to use this mount variant
    default: false
  horsemount.variant.mule:
    description: allows you to use this mount variant
    default: false
  horsemount.variant.donkey:
    description: allows you to use this mount variant
    default: false
  horsemount.variant.skeleton:
    description: allows you to use this mount variant
    default: false
  horsemount.variant.zombie:
    description: allows you to use this mount variant
    default: false
  horsemount.style.default:
    description: allows you to use this mount style
    default: false
  horsemount.style.white:
    description: allows you to use this mount style
    default: false
  horsemount.style.whitefield:
    description: allows you to use this mount style
    default: false
  horsemount.style.whitedots:
    description: allows you to use this mount style
    default: false
  horsemount.style.blackdots:
    description: allows you to use this mount style
    default: false
  horsemount.color.white:
    description: allows you to use this mount color
    default: false
  horsemount.color.creamy:
    description: allows you to use this mount color
    default: false
  horsemount.color.chestnut:
    description: allows you to use this mount color
    default: false
  horsemount.color.brown:
    description: allows you to use this mount color
    default: false
  horsemount.color.black:
    description: allows you to use this mount color
    default: false
  horsemount.color.gray:
    description: allows you to use this mount color
    default: false
  horsemount.color.darkbrown:
    description: allows you to use this mount color
    default: false